apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        app: orders-app
    spec:
      containers:
      - name: orders-app
        image: orders-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: TENANT_ID
          value: "47dd6b24-0b23-46b0-a662-776158d089ba"
        - name: AUTH_MS_URL
          value: "http://auth-service:8000"
        - name: PRODUCT_MS_URL
          value: "http://product-service:8002"
        - name: DB_HOST
          value: "orders-db-service"
        - name: DB_PORT
          value: "5432"