version: '3.8'

services:
  marketplace:
    build: .
    ports:
      - "8001:8001"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=db
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: