apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-app
        image: product-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        - name: TENANT_ID
          value: "47dd6b24-0b23-46b0-a662-776158d089ba"
        - name: AUTH_MS_URL
          value: "http://auth-service:8000"
        - name: TENANT_MS_URL
          value: "http://tenant-service:8003"
        - name: DB_HOST
          value: "product-db-service"
        - name: DB_PORT
          value: "5432"