version: '3.8'

services:
  # Node.js application service
  microservice:
    build: .
    image: auth-image:latest
    ports:
      - "8000:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  # ✅ Definisikan volume
