apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-app
  template:
    metadata:
      labels:
        app: tenant-app
    spec:
      containers:
      - name: tenant-app
        image: tenant-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
        env:
        - name: AUTH_MS_URL
          value: "http://auth-service:8000"
        - name: DB_HOST
          value: "tenant-db-service"
        - name: DB_PORT
          value: "5432"