apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      tolerations:
      - key: "reserved-for"
        operator: "Equal"
        value: "workload"
        effect: "NoSchedule"
      containers:
      - name: auth-app
        image: reiounagata/auth-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: TENANT_ID
          value: "47dd6b24-0b23-46b0-a662-776158d09ba"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "auth-db-service"
        - name: DB_PORT
          value: "5432"
        resources:
          requests:
            cpu: "0.2"    # 20% dari 1 vCPU t2.nano
            memory: "64Mi"  # Jangan lebih dari 256Mi!
          limits:
            cpu: "0.4"
            memory: "128Mi"
