apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-db
  template:
    metadata:
      labels:
        app: wishlist-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432